"""empty message

Revision ID: 4f241d1faeb2
Revises: 08b5e88ddb54
Create Date: 2022-08-10 09:57:37.991143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f241d1faeb2'
down_revision = '08b5e88ddb54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notebooks', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('users', sa.Column('scratch_pad', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'scratch_pad')
    op.drop_column('notebooks', 'updated_at')
    # ### end Alembic commands ###
